#!/usr/bin/env php
<?php

/**
 * MySite CMS console bootstrap file.
 *
 * @link https://github.com/ambirus/mysite-cms
 * @copyright Copyright (c) 2019 MySite CMS
 */

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require_once __DIR__ . DIRECTORY_SEPARATOR . 'protected' . DIRECTORY_SEPARATOR . 'bootstrap.php';
$config = require_once __DIR__ . DIRECTORY_SEPARATOR . 'protected' . DIRECTORY_SEPARATOR . 'console.php';

use src\App;
use src\I18n;

$i18n = new I18n();

try {
    $app = new App($config);
    $app->run();
} catch (Exception $e) {
    if (isset($config['debug']) && $config['debug'] == 1) {
        $message = $i18n->translate('{{%' . $e->getMessage() . '%}}');
        echo $message . "\n";
        echo $e->getFile() . ', ' . $e->getTraceAsString() . "\n";
    }
}